添加root权限下直接开启/关闭服务功能
zhongyi-tong/WeChatLuckyMoney pull request #211
Opened 2017-01-21 15:45 UTC by act262

增加root用户直接开启开启关闭红包服务的功能，在root的情况下可以直接打开服务而不用跳转到设置页手动打开。

2017-01-22 06:14 UTC, geeeeeeeeek commented
Good point! Consider adding in to 4.0 release.

2017-01-22 06:17 UTC, ray26 commented
测试完成后将会进行pr

2017-01-23 02:08 UTC, ray26 commented
你这个在我测试了一下，我的API25的设备获取了root权限，但是还是没有使用root权限，还是在无障碍打开的

2017-01-23 12:30 UTC, act262 commented
@ray26 你这个是什么软件root过来的？

2017-01-23 13:36 UTC, ray26 commented
@act262 mokee自带root，开发者选项里面的，我已经给adb和应用都给了root权限，而他没有弹出来wechatluckymoney请求root权限

2017-01-23 14:12 UTC, larryxiao625 requested changes
Not pass in the API25

2017-01-23 14:20 UTC, act262 commented
试试在这个`isRoot`方法中加入你手机root后的特征
```java
    /**
     * 判断当前手机是否有ROOT权限
     */
    public static boolean isRoot() {
        boolean root = false;
        try {
            // TODO: 2017/1/21 0021 需要判断多种root的情况
            if ((!new File("/su/bin/su").exists())) { // eu.chainfire.supersu
                root = false;
            } else {
                root = true;
            }
        } catch (Exception e) {
        }
        return root;
    }
```

2017-01-23 14:25 UTC, ray26 commented
我建议你别判断位置，很多rom改了位置的，建议用type或者which，毕竟现在还有一个systemless的root，su是在data里面新建一个块设备挂载然后boot里面加PATH的，command line tool，type su或者which du

2017-01-23 14:31 UTC, ray26 commented on app/src/main/java/xyz/monkeytong/hongbao/utils/AccessibilityUtil.java
> +            if ((!new File("/su/bin/su").exists())) { // eu.chainfire.supersu
我建议你别判断位置，很多rom改了位置的，建议用type或者which，毕竟现在还有一个systemless的root，su是在data里面新建一个块设备挂载然后boot里面加PATH的，command line tool，type su或者which du，type是built in的可能会好用点，你的路径就是新版的supersu的路径，不会修改system分区的方式；或者你改成运行shell command就可以了，type只要在PATH有就返回成功了
![qq20170123-0](https://cloud.githubusercontent.com/assets/6435613/22207783/7e0aabe6-e1bb-11e6-902f-70048042db64.png)

2017-02-03 04:41 UTC, closed without merging